In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

data= pd.read_csv('Responses)_new.csv')

In [2]:
data.head()

,Unnamed: 0,Unnamed: 1,Name of respondent/s,Age,Gender,Confidence in Product Safety:,Understanding of Supply Chain Processes:,Trust in the Pharmaceutical Industry:,Awareness of Environment-Friendly Practices:,Impact on Brand Loyalty:,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,NaN,NaN,Pravalika Das,20,Female,3,3,3,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Pratistha,20,Female,5,5,5,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Anoushka Mishra,20,Female,4,4,4,4,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Pratima Das,52,Female,5,4,5,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Sabita Kanan,55,Female,3,3,4,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data=data.dropna(axis=1)
data.head()

,Name of respondent/s,Age,Gender,Confidence in Product Safety:,Understanding of Supply Chain Processes:,Trust in the Pharmaceutical Industry:,Awareness of Environment-Friendly Practices:,Impact on Brand Loyalty:,Perception of Environmental Responsibility:,Influence on Purchasing Decisions:,...,Inclusion of Green Practices:,Perception of Waste Reduction:,Supply Chain Security Concerns:,Consumer Participation in Recycling Programs:,Impact on Competitive Advantage:,Public Perception of Regulatory Compliance:,Ethical Sourcing and Fair Trade Practices:,Perceived Impact on Health Outcomes:,Impact on Corporate Social Responsibility (CSR) Image:,Educational Initiatives on Transparency:
0,Pravalika Das,20,Female,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
1,Pratistha,20,Female,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
2,Anoushka Mishra,20,Female,4,4,4,4,3,5,4,...,2,3,2,3,3,4,5,3,3,4
3,Pratima Das,52,Female,5,4,5,5,5,4,5,...,4,4,4,5,5,4,4,5,4,4
4,Sabita Kanan,55,Female,3,3,4,3,4,4,3,...,3,4,4,4,4,4,4,5,4,3

In [4]:
#data['Gender']=data['Gender'].map({'Male':0, 'Female':1})
data.drop(['Gender','Age'],axis=1,inplace=True)

In [5]:
# Convert DataFrame to numeric type
data_numeric = data.apply(pd.to_numeric, errors='coerce')

# Drop rows where max value equals min value
data.drop(data_numeric.index[data_numeric.max(axis=1) == data_numeric.min(axis=1)].values, inplace=True)

In [6]:
data.set_index(data.columns[0])
df=data.T

In [7]:
df=df.drop(df.index[0])
df.head()

,2,3,4,5,6,7,9,10,11,12,...,146,147,148,149,150,152,153,154,155,156
Confidence in Product Safety:,4,5,3,5,5,5,4,4,5,2,...,3,4,3,4,5,5,4,4,4,5
Understanding of Supply Chain Processes:,4,4,3,3,2,4,4,2,3,2,...,3,2,4,3,3,4,3,4,4,3
Trust in the Pharmaceutical Industry:,4,5,4,5,4,5,5,2,5,3,...,4,5,4,4,3,4,4,5,3,5
Awareness of Environment-Friendly Practices:,4,5,3,5,2,3,5,3,3,3,...,2,3,2,2,4,2,4,5,4,3
Impact on Brand Loyalty:,3,5,4,5,5,4,2,4,5,4,...,3,3,4,4,3,4,4,5,4,5

In [30]:
# Normalize the data
normalized_df = (df - df.min()) / (df.max() - df.min())

# Construct the cause-effect matrix
cause_effect_matrix = normalized_df.values

# Calculate the influence matrix
influence_matrix = np.dot(cause_effect_matrix, cause_effect_matrix.T)
df1= pd.DataFrame(influence_matrix)
avg_matrix = (df1 - df1.min())/ (df1.max() - df1.min())

In [31]:
avg_matrix = avg_matrix * 6 + 1
avg_matrix = avg_matrix.round().astype(int)  # Round to integers
avg_matrix

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0    7   5   5   5   5   5   5   5   5   5   5   5   5   5   5   4   5   5   5
1    1   5   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
2    6   7   7   6   5   6   6   6   7   6   6   5   6   6   5   5   5   5   6
3    1   2   1   6   1   2   1   2   1   1   1   1   1   1   1   1   1   1   1
4    6   6   5   6   7   6   6   6   6   6   6   6   6   6   6   5   5   5   6
5    5   5   5   5   5   7   5   5   5   5   5   5   5   5   5   4   4   4   5
6    5   6   5   6   5   5   7   5   6   6   6   6   6   6   5   5   5   5   5
7    5   4   4   5   4   5   4   7   5   6   5   5   5   5   4   4   4   4   5
8    1   2   1   1   1   1   1   2   6   3   2   1   1   1   1   1   1   1   2
9    1   1   1   1   1   1   1   1   2   5   1   1   1   1   1   1   1   1   1
10   3   4   3   3   3   3   3   3   5   4   6   4   4   4   3   3   3   3   3
11   5   6   4   6   5   5   5   5   5   6   6   7   5   6   5   4   5   5   5
12   4   5   4   5   4   4   4   4   4   5   5   4   7   5   4   4   4   4   4
13   4   4   4   4   4   4   4   4   4   5   5   4   5   6   4   4   4   4   5
14   5   5   4   5   5   5   5   5   4   5   5   5   5   5   6   5   5   5   5
15   6   6   6   7   6   6   6   6   6   6   7   6   6   7   7   7   6   7   7
16   5   6   5   6   5   5   6   5   6   7   6   6   6   6   5   5   7   6   6
17   4   5   4   5   4   4   4   5   5   5   5   5   5   5   5   4   5   6   5
18   3   4   3   3   3   3   3   3   4   4   4   3   4   4   3   3   3   4   6

In [33]:
causal_factors = np.where(avg_matrix.sum(axis=1) > avg_matrix.sum(axis=0))[0]

effect_factors = np.where(avg_matrix.sum(axis=1) < avg_matrix.sum(axis=0))[0]

print("Causal Factors:")
for factor in causal_factors:
    print(f"Variable {factor}")

print("\nConsequence Factors:")
for factor in effect_factors:
    print(f"Variable {factor}")

Causal Factors:
Variable 0
Variable 2
Variable 4
Variable 5
Variable 6
Variable 7
Variable 11
Variable 14
Variable 15
Variable 16
Variable 17

Consequence Factors:
Variable 1
Variable 3
Variable 8
Variable 9
Variable 10
Variable 13
Variable 18

# Mathematical working step by step

In [34]:
avg_matrix['Ri']= np.sum(avg_matrix,axis=1)

In [35]:
avg_matrix.head()

   0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18   Ri
0  7  5  5  5  5  5  5  5  5  5   5   5   5   5   5   4   5   5   5   96
1  1  5  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   1   1   23
2  6  7  7  6  5  6  6  6  7  6   6   5   6   6   5   5   5   5   6  111
3  1  2  1  6  1  2  1  2  1  1   1   1   1   1   1   1   1   1   1   27
4  6  6  5  6  7  6  6  6  6  6   6   6   6   6   6   5   5   5   6  111

In [36]:
cj=np.vstack([avg_matrix,np.sum(avg_matrix,axis=0)])
avg_matrix_new= pd.DataFrame(cj)

In [37]:
avg_matrix_new

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,7,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,5,5,5,96
1,1,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,23
2,6,7,7,6,5,6,6,6,7,6,6,5,6,6,5,5,5,5,6,111
3,1,2,1,6,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,27
4,6,6,5,6,7,6,6,6,6,6,6,6,6,6,6,5,5,5,6,111
5,5,5,5,5,5,7,5,5,5,5,5,5,5,5,5,4,4,4,5,94
6,5,6,5,6,5,5,7,5,6,6,6,6,6,6,5,5,5,5,5,105
7,5,4,4,5,4,5,4,7,5,6,5,5,5,5,4,4,4,4,5,90
8,1,2,1,1,1,1,1,2,6,3,2,1,1,1,1,1,1,1,2,30
9,1,1,1,1,1,1,1,1,2,5,1,1,1,1,1,1,1,1,1,24
10,3,4,3,3,3,3,3,3,5,4,6,4,4,4,3,3,3,3,3,67
11,5,6,4,6,5,5,5,5,5,6,6,7,5,6,5,4,5,5,5,100
12,4,5,4,5,4,4,4,4,4,5,5,4,7,5,4,4,4,4,4,84
13,4,4,4,4,4,4,4,4,4,5,5,4,5,6,4,4,4,4,5,82
14,5,5,4,5,5,5,5,5,4,5,5,5,5,5,6,5,5,5,5,94
15,6,6,6,7,6,6,6,6,6,6,7,6,6,7,7,7,6,7,7,121
16,5,6,5,6,5,5,6,5,6,7,6,6,6,6,5,5,7,6,6,109
17,4,5,4,5,4,4,4,5,5,5,5,5,5,5,5,4,5,6,5,90
18,3,4,3,3,3,3,3,3,4,4,4,3,4,4,3,3,3,4,6,67
19,77,88,72,86,74,78,77,80,87,91,87,80,84,85,76,70,74,76,83,1525

In [38]:
avg_matrix_new.rename(index={19: 'Cj'}, inplace=True)
avg_matrix_new.rename(columns={19: 'Ri'}, inplace=True)

In [39]:
avg_matrix_new['Ri-Cj'] = avg_matrix_new.iloc[:, -1] - avg_matrix_new.iloc[-1, :]

In [40]:
avg_matrix_new

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,Ri,Ri-Cj
0,7,5,5,5,5,5,5,5,5,5,...,5,5,5,5,4,5,5,5,96,19.0
1,1,5,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,23,-65.0
2,6,7,7,6,5,6,6,6,7,6,...,5,6,6,5,5,5,5,6,111,39.0
3,1,2,1,6,1,2,1,2,1,1,...,1,1,1,1,1,1,1,1,27,-59.0
4,6,6,5,6,7,6,6,6,6,6,...,6,6,6,6,5,5,5,6,111,37.0
5,5,5,5,5,5,7,5,5,5,5,...,5,5,5,5,4,4,4,5,94,16.0
6,5,6,5,6,5,5,7,5,6,6,...,6,6,6,5,5,5,5,5,105,28.0
7,5,4,4,5,4,5,4,7,5,6,...,5,5,5,4,4,4,4,5,90,10.0
8,1,2,1,1,1,1,1,2,6,3,...,1,1,1,1,1,1,1,2,30,-57.0
9,1,1,1,1,1,1,1,1,2,5,...,1,1,1,1,1,1,1,1,24,-67.0
10,3,4,3,3,3,3,3,3,5,4,...,4,4,4,3,3,3,3,3,67,-20.0
11,5,6,4,6,5,5,5,5,5,6,...,7,5,6,5,4,5,5,5,100,20.0
12,4,5,4,5,4,4,4,4,4,5,...,4,7,5,4,4,4,4,4,84,0.0
13,4,4,4,4,4,4,4,4,4,5,...,4,5,6,4,4,4,4,5,82,-3.0
14,5,5,4,5,5,5,5,5,4,5,...,5,5,5,6,5,5,5,5,94,18.0
15,6,6,6,7,6,6,6,6,6,6,...,6,6,7,7,7,6,7,7,121,51.0
16,5,6,5,6,5,5,6,5,6,7,...,6,6,6,5,5,7,6,6,109,35.0
17,4,5,4,5,4,4,4,5,5,5,...,5,5,5,5,4,5,6,5,90,14.0
18,3,4,3,3,3,3,3,3,4,4,...,3,4,4,3,3,3,4,6,67,-16.0
Cj,77,88,72,86,74,78,77,80,87,91,...,80,84,85,76,70,74,76,83,1525,NaN

In [41]:
def func(value):
    if value<0:
        return 'Consequence'
    else: return 'Causal'

avg_matrix_new['Factors']= avg_matrix_new['Ri-Cj'].apply(func)

In [42]:
avg_matrix_new

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,Ri,Ri-Cj,Factors
0,7,5,5,5,5,5,5,5,5,5,...,5,5,5,4,5,5,5,96,19.0,Causal
1,1,5,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,23,-65.0,Consequence
2,6,7,7,6,5,6,6,6,7,6,...,6,6,5,5,5,5,6,111,39.0,Causal
3,1,2,1,6,1,2,1,2,1,1,...,1,1,1,1,1,1,1,27,-59.0,Consequence
4,6,6,5,6,7,6,6,6,6,6,...,6,6,6,5,5,5,6,111,37.0,Causal
5,5,5,5,5,5,7,5,5,5,5,...,5,5,5,4,4,4,5,94,16.0,Causal
6,5,6,5,6,5,5,7,5,6,6,...,6,6,5,5,5,5,5,105,28.0,Causal
7,5,4,4,5,4,5,4,7,5,6,...,5,5,4,4,4,4,5,90,10.0,Causal
8,1,2,1,1,1,1,1,2,6,3,...,1,1,1,1,1,1,2,30,-57.0,Consequence
9,1,1,1,1,1,1,1,1,2,5,...,1,1,1,1,1,1,1,24,-67.0,Consequence
10,3,4,3,3,3,3,3,3,5,4,...,4,4,3,3,3,3,3,67,-20.0,Consequence
11,5,6,4,6,5,5,5,5,5,6,...,5,6,5,4,5,5,5,100,20.0,Causal
12,4,5,4,5,4,4,4,4,4,5,...,7,5,4,4,4,4,4,84,0.0,Causal
13,4,4,4,4,4,4,4,4,4,5,...,5,6,4,4,4,4,5,82,-3.0,Consequence
14,5,5,4,5,5,5,5,5,4,5,...,5,5,6,5,5,5,5,94,18.0,Causal
15,6,6,6,7,6,6,6,6,6,6,...,6,7,7,7,6,7,7,121,51.0,Causal
16,5,6,5,6,5,5,6,5,6,7,...,6,6,5,5,7,6,6,109,35.0,Causal
17,4,5,4,5,4,4,4,5,5,5,...,5,5,5,4,5,6,5,90,14.0,Causal
18,3,4,3,3,3,3,3,3,4,4,...,4,4,3,3,3,4,6,67,-16.0,Consequence
Cj,77,88,72,86,74,78,77,80,87,91,...,84,85,76,70,74,76,83,1525,NaN,Causal