In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

data= pd.read_csv('Responses)_new.csv')

In [2]:
data.head()

,Unnamed: 0,Unnamed: 1,Name of respondent/s,Age,Gender,Confidence in Product Safety:,Understanding of Supply Chain Processes:,Trust in the Pharmaceutical Industry:,Awareness of Environment-Friendly Practices:,Impact on Brand Loyalty:,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,NaN,NaN,Pravalika Das,20,Female,3,3,3,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Pratistha,20,Female,5,5,5,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Anoushka Mishra,20,Female,4,4,4,4,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Pratima Das,52,Female,5,4,5,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Sabita Kanan,55,Female,3,3,4,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data=data.dropna(axis=1)
data.head()

,Name of respondent/s,Age,Gender,Confidence in Product Safety:,Understanding of Supply Chain Processes:,Trust in the Pharmaceutical Industry:,Awareness of Environment-Friendly Practices:,Impact on Brand Loyalty:,Perception of Environmental Responsibility:,Influence on Purchasing Decisions:,...,Inclusion of Green Practices:,Perception of Waste Reduction:,Supply Chain Security Concerns:,Consumer Participation in Recycling Programs:,Impact on Competitive Advantage:,Public Perception of Regulatory Compliance:,Ethical Sourcing and Fair Trade Practices:,Perceived Impact on Health Outcomes:,Impact on Corporate Social Responsibility (CSR) Image:,Educational Initiatives on Transparency:
0,Pravalika Das,20,Female,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
1,Pratistha,20,Female,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
2,Anoushka Mishra,20,Female,4,4,4,4,3,5,4,...,2,3,2,3,3,4,5,3,3,4
3,Pratima Das,52,Female,5,4,5,5,5,4,5,...,4,4,4,5,5,4,4,5,4,4
4,Sabita Kanan,55,Female,3,3,4,3,4,4,3,...,3,4,4,4,4,4,4,5,4,3

In [4]:
#data['Gender']=data['Gender'].map({'Male':0, 'Female':1})
data.drop(['Gender','Age'],axis=1,inplace=True)

In [5]:
# Convert DataFrame to numeric type
data_numeric = data.apply(pd.to_numeric, errors='coerce')

# Drop rows where max value equals min value
data.drop(data_numeric.index[data_numeric.max(axis=1) == data_numeric.min(axis=1)].values, inplace=True)

In [6]:
data.set_index(data.columns[0])
df=data.T

In [7]:
df=df.drop(df.index[0])
df.head()

,2,3,4,5,6,7,9,10,11,12,...,146,147,148,149,150,152,153,154,155,156
Confidence in Product Safety:,4,5,3,5,5,5,4,4,5,2,...,3,4,3,4,5,5,4,4,4,5
Understanding of Supply Chain Processes:,4,4,3,3,2,4,4,2,3,2,...,3,2,4,3,3,4,3,4,4,3
Trust in the Pharmaceutical Industry:,4,5,4,5,4,5,5,2,5,3,...,4,5,4,4,3,4,4,5,3,5
Awareness of Environment-Friendly Practices:,4,5,3,5,2,3,5,3,3,3,...,2,3,2,2,4,2,4,5,4,3
Impact on Brand Loyalty:,3,5,4,5,5,4,2,4,5,4,...,3,3,4,4,3,4,4,5,4,5

In [8]:
# Construct the cause-effect matrix
cause_effect_matrix = df.values

# Calculate the influence matrix
influence_matrix = np.dot(cause_effect_matrix, cause_effect_matrix.T)
df1= pd.DataFrame(influence_matrix)
avg_matrix = (df1 - df1.min())/ (df1.max() - df1.min())

In [9]:
avg_matrix

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.935792,0.84009,0.788608,0.81323,0.828387,0.798064,0.797315,0.804082,0.813187,0.794492,0.831346,0.827725,0.801196,0.792023,0.780914,0.718478,0.781491,0.779412,0.8032
1,0.0,0.245495,0.001266,0.019455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004484,0.0,0.0,0.0,0.0,0.0,0.008
2,0.942623,0.993243,1.0,0.951362,0.934194,0.946058,0.919463,0.921088,0.969231,0.932203,0.931857,0.908479,0.901345,0.915954,0.884409,0.833696,0.903599,0.877005,0.912
3,0.170765,0.202703,0.163291,0.441634,0.187097,0.190871,0.167785,0.183673,0.134066,0.169492,0.178876,0.185734,0.167414,0.168091,0.173387,0.163043,0.167095,0.171123,0.1568
4,0.923497,0.916667,0.874684,0.918288,1.0,0.917012,0.883221,0.892517,0.89011,0.870763,0.901193,0.911171,0.896861,0.921652,0.876344,0.797826,0.852185,0.868984,0.8704
5,0.756831,0.788288,0.751899,0.793774,0.781935,0.878285,0.742282,0.74966,0.769231,0.745763,0.780239,0.741588,0.766816,0.747863,0.740591,0.683696,0.718509,0.709893,0.72
6,0.826503,0.864865,0.796203,0.83463,0.819355,0.811895,0.915436,0.797279,0.868132,0.82839,0.827939,0.830417,0.807175,0.831909,0.790323,0.744565,0.804627,0.784759,0.8096
7,0.73224,0.716216,0.702532,0.725681,0.731613,0.717842,0.697987,0.868027,0.769231,0.760593,0.727428,0.7214,0.717489,0.705128,0.678763,0.661957,0.691517,0.707219,0.7088
8,0.050546,0.09009,0.051899,0.040856,0.049032,0.055325,0.068456,0.097959,0.362637,0.190678,0.107325,0.060565,0.040359,0.048433,0.017473,0.055435,0.051414,0.052139,0.0672
9,0.002732,0.0,0.0,0.0,0.005161,0.002766,0.009396,0.055782,0.10989,0.209746,0.035775,0.018843,0.0,0.012821,0.004032,0.030435,0.01671,0.01738,0.0
10,0.435792,0.459459,0.393671,0.445525,0.420645,0.431535,0.410738,0.42585,0.498901,0.476695,0.666099,0.46568,0.433483,0.415954,0.413978,0.377174,0.428021,0.427807,0.3936
11,0.814208,0.797297,0.74557,0.801556,0.805161,0.767635,0.787919,0.778231,0.789011,0.779661,0.844974,0.890983,0.769806,0.801994,0.776882,0.709783,0.77635,0.782086,0.752
12,0.635246,0.686937,0.588608,0.649805,0.63871,0.643154,0.614765,0.631293,0.635165,0.639831,0.660988,0.623149,0.793722,0.639601,0.615591,0.572826,0.613111,0.59492,0.6176
13,0.654372,0.666667,0.631646,0.649805,0.691613,0.651452,0.665772,0.643537,0.637363,0.646186,0.654174,0.679677,0.662182,0.779202,0.659946,0.602174,0.647815,0.645722,0.6368
14,0.751366,0.77027,0.708861,0.7607,0.757419,0.751037,0.732886,0.719728,0.692308,0.730932,0.759796,0.761777,0.744395,0.764957,0.846774,0.697826,0.724936,0.741979,0.7264
15,1.0,1.0,0.975949,1.0,0.994839,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
16,0.851093,0.873874,0.824051,0.85214,0.830968,0.825726,0.845638,0.827211,0.852747,0.849576,0.88075,0.858681,0.841555,0.849003,0.819892,0.784783,0.930591,0.851604,0.8448
17,0.734973,0.738739,0.688608,0.731518,0.736774,0.704011,0.712752,0.733333,0.718681,0.722458,0.756388,0.752355,0.704036,0.733618,0.727151,0.686957,0.741645,0.81016,0.7472
18,0.506831,0.556306,0.470886,0.505837,0.489032,0.473029,0.488591,0.49932,0.536264,0.512712,0.483816,0.48183,0.487294,0.490028,0.475806,0.459783,0.491003,0.509358,0.6432

In [10]:
avg_matrix = avg_matrix * 6 + 1
avg_matrix = avg_matrix.round().astype(int)  # Round to integers
avg_matrix

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0    6   6   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5
1    1   2   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
2    6   6   7   6   6   6   6   6   6   6   6   6   6   6   6   6   6   6   6
3    2   2   1   3   2   2   2   2   1   2   2   2   2   2   2   1   2   2   1
4    6   6   6   6   7   6   6   6   6   6   6   6   6   6   6   5   6   6   6
5    5   5   5   5   5   6   5   5   5   5   5   5   5   5   5   5   5   5   5
6    5   6   5   6   5   5   6   5   6   5   5   5   5   5   5   5   5   5   5
7    5   5   5   5   5   5   5   6   5   5   5   5   5   5   5   4   5   5   5
8    1   1   1   1   1   1   1   1   3   2   1   1   1   1   1   1   1   1   1
9    1   1   1   1   1   1   1   1   1   2   1   1   1   1   1   1   1   1   1
10   3   3   3   3   3   3   3   3   3   3   4   3   3   3   3   3   3   3   3
11   5   5   5   5   5   5   5   5   5   5   6   6   5   5   5   5   5   5   5
12   4   5   4   4   4   4   4   4   4   4   4   4   5   4   4   4   4   4   4
13   4   5   4   4   5   4   4   4   4   4   4   5   4   5   4   4   4   4   4
14   5   5   5   5   5   5   5   5   5   5   5   5   5   5   6   5   5   5   5
15   7   7   6   7   6   7   7   7   7   7   7   7   7   7   7   7   7   7   7
16   6   6   5   6   5   5   6   5   6   6   6   6   6   6   5   5   6   6   6
17   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5   5
18   4   4   3   4   3   3   3   3   4   4   3   3   3   3   3   3   3   4   4

In [11]:
causal_factors = np.where(avg_matrix.sum(axis=1) > avg_matrix.sum(axis=0))[0]

effect_factors = np.where(avg_matrix.sum(axis=1) < avg_matrix.sum(axis=0))[0]

print("Causal Factors:")
for factor in causal_factors:
    print(f"Variable {factor}")

print("\nConsequence Factors:")
for factor in effect_factors:
    print(f"Variable {factor}")

Causal Factors:
Variable 0
Variable 2
Variable 4
Variable 5
Variable 6
Variable 7
Variable 11
Variable 14
Variable 15
Variable 16
Variable 17

Consequence Factors:
Variable 1
Variable 3
Variable 8
Variable 9
Variable 10
Variable 12
Variable 18

# Mathematical working step by step

In [12]:
avg_matrix['Ri']= np.sum(avg_matrix,axis=1)

In [13]:
avg_matrix.head()

   0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18   Ri
0  6  6  5  5  5  5  5  5  5  5   5   5   5   5   5   5   5   5   5   97
1  1  2  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   1   1   20
2  6  6  7  6  6  6  6  6  6  6   6   6   6   6   6   6   6   6   6  115
3  2  2  1  3  2  2  2  2  1  2   2   2   2   2   2   1   2   2   1   35
4  6  6  6  6  7  6  6  6  6  6   6   6   6   6   6   5   6   6   6  114

In [14]:
cj=np.vstack([avg_matrix,np.sum(avg_matrix,axis=0)])
avg_matrix_new= pd.DataFrame(cj)

In [15]:
avg_matrix_new

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,97
1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,20
2,6,6,7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,115
3,2,2,1,3,2,2,2,2,1,2,2,2,2,2,2,1,2,2,1,35
4,6,6,6,6,7,6,6,6,6,6,6,6,6,6,6,5,6,6,6,114
5,5,5,5,5,5,6,5,5,5,5,5,5,5,5,5,5,5,5,5,96
6,5,6,5,6,5,5,6,5,6,5,5,5,5,5,5,5,5,5,5,99
7,5,5,5,5,5,5,5,6,5,5,5,5,5,5,5,4,5,5,5,95
8,1,1,1,1,1,1,1,1,3,2,1,1,1,1,1,1,1,1,1,22
9,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,20
10,3,3,3,3,3,3,3,3,3,3,4,3,3,3,3,3,3,3,3,58
11,5,5,5,5,5,5,5,5,5,5,6,6,5,5,5,5,5,5,5,97
12,4,5,4,4,4,4,4,4,4,4,4,4,5,4,4,4,4,4,4,78
13,4,5,4,4,5,4,4,4,4,4,4,5,4,5,4,4,4,4,4,80
14,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,5,5,5,5,96
15,7,7,6,7,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,131
16,6,6,5,6,5,5,6,5,6,6,6,6,6,6,5,5,6,6,6,108
17,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,95
18,4,4,3,4,3,3,3,3,4,4,3,3,3,3,3,3,3,4,4,64
19,81,85,77,82,79,79,80,79,82,82,81,81,80,80,79,75,79,80,79,1520

In [16]:
avg_matrix_new.rename(index={19: 'Cj'}, inplace=True)
avg_matrix_new.rename(columns={19: 'Ri'}, inplace=True)

In [17]:
avg_matrix_new['Ri-Cj'] = avg_matrix_new.iloc[:, -1] - avg_matrix_new.iloc[-1, :]

In [18]:
avg_matrix_new

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,Ri,Ri-Cj
0,6,6,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,97,16.0
1,1,2,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,20,-65.0
2,6,6,7,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,115,38.0
3,2,2,1,3,2,2,2,2,1,2,...,2,2,2,2,1,2,2,1,35,-47.0
4,6,6,6,6,7,6,6,6,6,6,...,6,6,6,6,5,6,6,6,114,35.0
5,5,5,5,5,5,6,5,5,5,5,...,5,5,5,5,5,5,5,5,96,17.0
6,5,6,5,6,5,5,6,5,6,5,...,5,5,5,5,5,5,5,5,99,19.0
7,5,5,5,5,5,5,5,6,5,5,...,5,5,5,5,4,5,5,5,95,16.0
8,1,1,1,1,1,1,1,1,3,2,...,1,1,1,1,1,1,1,1,22,-60.0
9,1,1,1,1,1,1,1,1,1,2,...,1,1,1,1,1,1,1,1,20,-62.0
10,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,58,-23.0
11,5,5,5,5,5,5,5,5,5,5,...,6,5,5,5,5,5,5,5,97,16.0
12,4,5,4,4,4,4,4,4,4,4,...,4,5,4,4,4,4,4,4,78,-2.0
13,4,5,4,4,5,4,4,4,4,4,...,5,4,5,4,4,4,4,4,80,0.0
14,5,5,5,5,5,5,5,5,5,5,...,5,5,5,6,5,5,5,5,96,17.0
15,7,7,6,7,6,7,7,7,7,7,...,7,7,7,7,7,7,7,7,131,56.0
16,6,6,5,6,5,5,6,5,6,6,...,6,6,6,5,5,6,6,6,108,29.0
17,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,95,15.0
18,4,4,3,4,3,3,3,3,4,4,...,3,3,3,3,3,3,4,4,64,-15.0
Cj,81,85,77,82,79,79,80,79,82,82,...,81,80,80,79,75,79,80,79,1520,NaN

In [19]:
def func(value):
    if value<0:
        return 'Consequence'
    else: return 'Causal'

avg_matrix_new['Factors']= avg_matrix_new['Ri-Cj'].apply(func)

In [20]:
avg_matrix_new

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,Ri,Ri-Cj,Factors
0,6,6,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,97,16.0,Causal
1,1,2,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,20,-65.0,Consequence
2,6,6,7,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,115,38.0,Causal
3,2,2,1,3,2,2,2,2,1,2,...,2,2,2,1,2,2,1,35,-47.0,Consequence
4,6,6,6,6,7,6,6,6,6,6,...,6,6,6,5,6,6,6,114,35.0,Causal
5,5,5,5,5,5,6,5,5,5,5,...,5,5,5,5,5,5,5,96,17.0,Causal
6,5,6,5,6,5,5,6,5,6,5,...,5,5,5,5,5,5,5,99,19.0,Causal
7,5,5,5,5,5,5,5,6,5,5,...,5,5,5,4,5,5,5,95,16.0,Causal
8,1,1,1,1,1,1,1,1,3,2,...,1,1,1,1,1,1,1,22,-60.0,Consequence
9,1,1,1,1,1,1,1,1,1,2,...,1,1,1,1,1,1,1,20,-62.0,Consequence
10,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,58,-23.0,Consequence
11,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,97,16.0,Causal
12,4,5,4,4,4,4,4,4,4,4,...,5,4,4,4,4,4,4,78,-2.0,Consequence
13,4,5,4,4,5,4,4,4,4,4,...,4,5,4,4,4,4,4,80,0.0,Causal
14,5,5,5,5,5,5,5,5,5,5,...,5,5,6,5,5,5,5,96,17.0,Causal
15,7,7,6,7,6,7,7,7,7,7,...,7,7,7,7,7,7,7,131,56.0,Causal
16,6,6,5,6,5,5,6,5,6,6,...,6,6,5,5,6,6,6,108,29.0,Causal
17,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,95,15.0,Causal
18,4,4,3,4,3,3,3,3,4,4,...,3,3,3,3,3,4,4,64,-15.0,Consequence
Cj,81,85,77,82,79,79,80,79,82,82,...,80,80,79,75,79,80,79,1520,NaN,Causal